apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: add
spec:
  params:
    - name: x
      type: string
    - name: y
      type: string
  results:
    - name: sum
      description: Sum of two numbers.
  image: ubuntu
  command:
    - /bin/sh
    - -c
  args:
    - x1 = $(echo "$x")
      y1 = $(echo "$y")
      sum = $((x1 + y1))
      echo "$sum" > /tekton/results/sum
