apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: add
spec:
  params:
    - name: num1
      type: string
    - name: num2
      type: string
  results:
    - name: sum
      description: Sum of two numbers.
  image: ubuntu
  command:
    - /bin/sh
    - -c
  args:
    - x1=$(echo "$num1")
      y1=$(echo "$num2")
      sum=$((x1+y1))
      echo "$sum" > /tekton/results/sum
