apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: echo
spec:
  params:
    - name: message
      type: string
  results:
    - name: output
      description: What was echoed.
  image: ubuntu
  command:
    - /bin/sh
    - -c
  args:
    - echo "$message"
      echo "$message" > /tekton/results/output
